### ISSUE TITLE
Bugs prod_analysis-cfa.rmd & prod_prep-data

### ISSUE THREAD

**Issue by juancarloscastillo** [juancarloscastillo/merit-scale#7]
no genera html al compilar, dentro de los warnings:
Error: path for html_dependency not found: C:/Users/Julio/Documents/R/win-library/3.6/kableExtra/kePrint-0.0.1

... hace referencia a dependencia local en tu computador Julio, probablemente es por diferencia en versiones de librerías. Ver forma de agregar info de versiones de paquetes usados al html.

... y prop_prep-data tampoco genera html

**Comment by jciturras** [comment]
Hice un test, con un pullrequest.  ¿Podrías ver si es factible reproducir el sitio en tu computador?

Quedo atento...

**Comment by juancarloscastillo** [comment]
resuelto
